apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: my-project
  name: backend-backup
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backup
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: backup
        tier: backend
    spec:
      restartPolicy: Always

      containers:
      - name: backend-backup
        image: lordslair/easydbbackup:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: 32Mi
            cpu: 50m
          requests:
            memory: 16Mi
            cpu: 10m
        env:
          # MySQL/MarisDB related variables
          - name: MYSQL_DUMP
            valueFrom:
              secretKeyRef:
                name: my-backup-secret
                key: mysql-dump
          - name: MySQL_DB_LIST
            valueFrom:
              secretKeyRef:
                name: my-backup-secret
                key: mysql-dblist
          - name: MySQL_DB_HOST
            valueFrom:
              secretKeyRef:
                name: my-backup-secret
                key: mysql-dbhost
          - name: MySQL_DB_PORT
            valueFrom:
              secretKeyRef:
                name: my-mariadb-secret
                key: mysql-port
          - name: MySQL_DB_PASS
            valueFrom:
              secretKeyRef:
                name: my-mariadb-secret
                key: mysql-pass
          - name: MySQL_DB_USER
            valueFrom:
              secretKeyRef:
                name: my-mariadb-secret
                key: mysql-user

          - name: PCA_USER
            valueFrom:
              secretKeyRef:
                name: my-backup-secret
                key: pcauser
          - name: PCA_PASS
            valueFrom:
              secretKeyRef:
                name: my-backup-secret
                key: pcapass
          - name: PCA_HOST
            valueFrom:
              secretKeyRef:
                name: my-backup-secret
                key: pcahost
          - name: PCA_DIR
            valueFrom:
              secretKeyRef:
                name: my-backup-secret
                key: pcadir

          # Redis related variables
          - name: REDIS_DUMP
            valueFrom:
              secretKeyRef:
                name: my-backup-secret
                key: redis-dump
          - name: REDIS_DB_HOST
            valueFrom:
              secretKeyRef:
                name: my-redis-secret
                key: redis-host
          - name: REDIS_DB_PORT
            valueFrom:
              secretKeyRef:
                name: my-redis-secret
                key: redis-port
