apiVersion: v1
kind: Secret

metadata:
  namespace: my-project
  name: my-backup-secret
type: Opaque
stringData:
  mysql-dblist: 'my-database,mysql'
  mysql-dbhost: 'my.mariadb.host'
  pcauser: 'pca'
  pcapass: 'MyArchivePassword'
  pcahost: 'my.pca.host'
  pcadir: 'backups/mariadb'
  mysql-dump: 'True'
  redis-dump: 'True'
  mongodb-dump: 'True'
  mongodb-export: 'True'
  mongodb-dblist: 'admin,config,my-collection'
  log-info: 'True'
  log-date: 'True'
  remote-path: 'my-bucket/my-path'
  remote-s3-access-key: '<remote-s3-access-key>'
  remote-s3-secret-key: '<remote-s3-secret-key>'
---
apiVersion: v1
kind: Secret

metadata:
  namespace: my-project
  name: my-mariadb-secret
type: Opaque
stringData:
  mysql-user: 'root'
  mysql-pass: 'MySQLPassword'
  mysql-port: '3306'
---
apiVersion: v1
kind: Secret

metadata:
  namespace: my-project
  name: my-redis-secret
type: Opaque
stringData:
  redis-host: 'my.redis.host'
  redis-port: '6379'
---
apiVersion: v1
kind: Secret

metadata:
  namespace: my-project
  name: my-mongodb-secret
type: Opaque
stringData:
  mongodb-host: 'my.mongodb.host'
  mongodb-user: '<mongodb-user>'
  mongodb-pass: '<mongodb-pass>'
  mongodb-port: '27017'