apiVersion: v1
kind: Secret

metadata:
  namespace: my-project
  name: my-backup-secret
type: Opaque
stringData:
  mysql-dblist: 'my-database,mysql'
  mysql-dbhost: 'my.mariadb.host'
  pcauser: 'pca'
  pcapass: 'MyArchivePassword'
  pcahost: 'my.pca.host'
  pcadir: 'backups/mariadb'
  mysql-dump: 'True'
  redis-dump: 'True'
---
apiVersion: v1
kind: Secret

metadata:
  namespace: my-project
  name: my-mariadb-secret
type: Opaque
stringData:
  mysql-user: 'root'
  mysql-pass: 'MySQLPassword'
  mysql-port: '3306'
---
apiVersion: v1
kind: Secret

metadata:
  namespace: my-project
  name: my-redis-secret
type: Opaque
stringData:
  redis-host: 'my.redis.host'
  redis-port: '6379'
